version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Fetching BUILD_UI flag..."
      - BUILD_UI=$(aws ssm get-parameter --name "/pipeline/BUILD_UI" --with-decryption --query "Parameter.Value" --output text)
      - echo "BUILD_UI is $BUILD_UI"
      - echo "$BUILD_UI" > build_flag.txt
      - rm -rf target/*.jar || true  # Clean up any old builds

  pre_build:
    commands:
      - echo "Pre-build step: cleaning"
      - mvn clean

  build:
    commands:
      - if [ "$(cat build_flag.txt)" = "false" ]; then echo "Skipping actual UI build phase"; exit 0; fi
      - echo "Running mvn package1"
      - mvn package -DskipTests=true

  post_build:
    commands:
      - if [ "$(cat build_flag.txt)" = "false" ]; then echo "Resetting flag only (no build done)"; else echo "Resetting BUILD_UI flag to false"; fi
      - aws ssm put-parameter --name "/pipeline/BUILD_UI" --value "false" --type "String" --overwrite

artifacts:
  files:
    - target/*.jar
