version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Fetching BUILD_UI flag..."
      - BUILD_UI=$(aws ssm get-parameter --name "/pipeline/BUILD_UI" --with-decryption --query "Parameter.Value" --output text)
      - echo "BUILD_UI is $BUILD_UI"
      - if [ "$BUILD_UI" = "false" ]; then echo "Skipping UI build"; exit 0; fi
  pre_build:
    commands:
      - mvn clean
  build:
    commands:
      - mvn package -DskipTests=true
  post_build:
    commands:
      - echo "Resetting BUILD_UI flag to false"
      - aws ssm put-parameter --name "/pipeline/BUILD_UI" --value "false" --type "String" --overwrite
      - echo "test ui trigger"

artifacts:
  files:
    - target/*.jar
