version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - if [ -f .last_built_commit ] && [ "$(cat .last_built_commit)" = "$CODEBUILD_RESOLVED_SOURCE_VERSION" ]; then
        echo "No changes in UI source. Skipping build.";
        exit 0;
        fi
  pre_build:
    commands:
      - mvn clean
  build:
    commands:
      - mvn package -DskipTests=true
  post_build:
    commands:
      - echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" > .last_built_commit

artifacts:
  files:
    - target/*.jar
    - .last_built_commit